import { ProductDNA, TweetOpportunity, PricingTier } from '@/types';

export const DEFAULT_PRODUCT_DNA: ProductDNA = {
  id: 'snypex-default',
  name: 'snypeX',
  tagline: 'Turn viral tweets in your niche into your customer acquisition pipeline.',
  targetAudience: 'Indie hackers, SaaS founders, and creators wanting inbound leads on X',
  differentiator: 'Spots breakout tweets in first 90 mins and generates non-bot data-backed replies with 1-click X intent.',
  url: 'https://snypex.com',
  tone: 'founder',
};

export const SAMPLE_PRODUCTS: ProductDNA[] = [
  DEFAULT_PRODUCT_DNA,
  {
    id: 'videoflow-ai',
    name: 'VideoFlow AI',
    tagline: 'Turn long podcasts into 10 viral TikToks and Shorts in 60 seconds.',
    targetAudience: 'Podcasters, YouTubers, and agency video editors',
    differentiator: 'Auto-detects high-retention hooks and generates 99% accurate animated captions.',
    url: 'https://videoflow.ai',
    tone: 'punchy',
  },
  {
    id: 'coldping',
    name: 'ColdPing',
    tagline: 'B2B cold email deliverability and warm-up that guarantees 70%+ open rates.',
    targetAudience: 'Agency owners, B2B sales reps, and growth hackers',
    differentiator: 'Dedicated private IP pools with AI inbox rotation to avoid spam filters.',
    url: 'https://coldping.io',
    tone: 'analytical',
  },
];

export const MOCK_TWEET_OPPORTUNITIES: TweetOpportunity[] = [
  {
    id: 'tweet-1',
    author: {
      name: 'Pieter Levels',
      handle: 'levelsio',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      verified: true,
      followers: '540K',
    },
    text: "Most SaaS landing pages lose 70% of potential buyers because they hide their pricing behind a 'Book a Demo' form. If your target is indie builders or SMBs, public transparent pricing will 3x your conversions overnight.",
    createdAtFormatted: '42m ago',
    minutesAgo: 42,
    likes: 480,
    retweets: 62,
    repliesCount: 88,
    velocityLikesPerHour: 685,
    badge: 'hot',
    badgeLabel: '🔥 Breakout (42m ago • 685 likes/hr)',
    opportunityInsight: 'Pieter is attacking gated enterprise sales flows. Perfect timing to share real conversion data or relate to transparent product pricing.',
    niche: 'SaaS & Indie Hacking',
    tweetUrl: 'https://x.com/levelsio/status/1789012345678901234',
  },
  {
    id: 'tweet-2',
    author: {
      name: 'Tibo',
      handle: 'tibo_maker',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      verified: true,
      followers: '142K',
    },
    text: "Question for creators and founders: What is your actual stack to turn viral X/Twitter impressions into email subscribers or paying customers? Looking for tools that don't feel like spam bots.",
    createdAtFormatted: '1h 15m ago',
    minutesAgo: 75,
    likes: 215,
    retweets: 18,
    repliesCount: 114,
    velocityLikesPerHour: 172,
    badge: 'lead',
    badgeLabel: '💡 High-Intent Lead (Direct question)',
    opportunityInsight: 'OP is explicitly asking for tool recommendations to capture audience from X without looking like a bot. Direct match for your value prop!',
    niche: 'Audience & Growth',
    tweetUrl: 'https://x.com/tibo_maker/status/1789012345678901235',
  },
  {
    id: 'tweet-3',
    author: {
      name: 'Sahil Lavingia',
      handle: 'shl',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      verified: true,
      followers: '330K',
    },
    text: "Building an audience first before building a product is becoming overrated. The best founders build a tiny tool that solves an acute painful itch, and the audience organically rallies around the solution.",
    createdAtFormatted: '2h 10m ago',
    minutesAgo: 130,
    likes: 890,
    retweets: 104,
    repliesCount: 230,
    velocityLikesPerHour: 410,
    badge: 'debate',
    badgeLabel: '⚡ High Debate (Audience vs Tool first)',
    opportunityInsight: 'Controversial philosophical debate. High comment volume. Dropping a nuanced contrarian hook here will yield dozens of secondary replies.',
    niche: 'Startups & Bootstrapping',
    tweetUrl: 'https://x.com/shl/status/1789012345678901236',
  },
  {
    id: 'tweet-4',
    author: {
      name: 'Greg Isenberg',
      handle: 'gregisenberg',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      verified: true,
      followers: '280K',
    },
    text: "The reply section of viral tweets on X is the new Google Search for discovery. The person who drops the most insightful summary or counter-data in the top 3 replies gets more profile clicks than the original author.",
    createdAtFormatted: '3h 30m ago',
    minutesAgo: 210,
    likes: 1240,
    retweets: 180,
    repliesCount: 165,
    velocityLikesPerHour: 354,
    badge: 'hot',
    badgeLabel: '🔥 Trending in Growth',
    opportunityInsight: 'Greg is validating your exact methodology. Backing up his point with real engagement statistics will establish massive credibility.',
    niche: 'Social Media & Growth',
    tweetUrl: 'https://x.com/gregisenberg/status/1789012345678901237',
  },
  {
    id: 'tweet-5',
    author: {
      name: 'Marc Lou',
      handle: 'marc_louvion',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      verified: true,
      followers: '115K',
    },
    text: "If you spend 4 hours coding a feature and 0 minutes distributing it, you don't have a business—you have a private hobby. What is your daily distribution routine?",
    createdAtFormatted: '50m ago',
    minutesAgo: 50,
    likes: 310,
    retweets: 42,
    repliesCount: 79,
    velocityLikesPerHour: 372,
    badge: 'lead',
    badgeLabel: '💡 Question (Distribution Routine)',
    opportunityInsight: 'OP is asking founders for their concrete distribution workflow. Explain a 10-minute daily snyping routine to show extreme efficiency.',
    niche: 'SaaS & Indie Hacking',
    tweetUrl: 'https://x.com/marc_louvion/status/1789012345678901238',
  },
];

export const PRICING_TIERS: PricingTier[] = [
  {
    id: 'starter',
    name: 'Starter',
    badge: 'Solo Founder',
    priceMonthly: 19,
    priceYearly: 15,
    description: 'Perfect for solo founders and indie hackers building their first inbound pipeline on X.',
    features: [
      '1 Active Product Profile',
      '50 High-Authority Snypes / month',
      'Track up to 15 Niche Leaders',
      'Real-time Opportunity Radar (Hot Posts)',
      '1-Click Post to X Intent',
      'Standard 3-Angle Generator',
    ],
    cta: 'Start Snyping Free',
    popular: false,
  },
  {
    id: 'pro',
    name: 'Growth & Pro',
    badge: 'Most Popular',
    priceMonthly: 39,
    priceYearly: 31,
    description: 'For serious builders and creators aiming to dominate their niche comment sections daily.',
    features: [
      '3 Active Product Profiles',
      'Unlimited High-Authority Snypes',
      'Track up to 60 Niche Leaders',
      'Direct "Lead Question" Buying Alerts',
      'Anti-Slop Voice Calibration',
      'Live Web Citation & Stats Verification',
      'Priority 15-Minute Radar Scan Speed',
      'Saved Snippet & Hook Vault',
    ],
    cta: 'Claim Pro Access',
    popular: true,
  },
  {
    id: 'agency',
    name: 'Agency & Scale',
    badge: 'High Velocity',
    priceMonthly: 79,
    priceYearly: 63,
    description: 'For growth agencies and serial builders managing multiple client brands or SaaS ventures.',
    features: [
      'Unlimited Product Profiles',
      'Multi-Account Team Collaboration (3 Seats)',
      'Unlimited Niche Influencer Tracking',
      'Custom Brand Voice & Persona Fine-Tuning',
      'Exportable Inbound Analytics & Click Tracker',
      'Dedicated Webhook & API Access',
      'Private Slack / Discord Strategy Support',
    ],
    cta: 'Upgrade to Scale',
    popular: false,
  },
];
